import { LayoutDashboard,FolderGit2,Mail,Handshake,Code2,User,Dock,Info,HandPlatter } from "lucide-react"
export const navItem = [
  {
    title:"Herro",
    href:"/dashboard/herro",
    icon:User
  },
  {
    title:"About",
    href:"/dashboard/about",
    icon:Info
  },
  {
    title:"Skill",
    href:"/dashboard/skill",
    icon:Code2
  },
  {
    title:"Service",
    href:"/dashboard/service",
    icon:HandPlatter
  },
  {
    title:"Project",
    href:"/dashboard/project",
    icon:FolderGit2
  },
  {
    title:"Blog",
    href:"/dashboard/blog",
    icon:Dock
  },
  {
    title:"Contact",
    href:"/dashboard/contact",
    icon:Handshake
  },
  {
    title:"Message",
    href:"/dashboard/message",
    icon:Mail
  },
  ]